CREATE TABLE IF NOT EXISTS `Users` (`User_ID` INT NOT NULL AUTO_INCREMENT
	,`Email` VARCHAR(100) UNIQUE NOT NULL
  	,`Fname` VARCHAR(60) NOT NULL
  	,`Lname` VARCHAR(60) NOT NULL
  	,`Username` VARCHAR(60) UNIQUE NOT NULL
	,`Password` VARCHAR(60) NOT NULL
	,`Create_Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	,PRIMARY KEY (`User_ID`)
	)


CREATE TABLE IF NOT EXISTS `Session_Tokens` (`Session_ID` INT NOT NULL AUTO_INCREMENT
  	,`Session_Create_Date` DATETIME2
	,`Session_Start_Time` DATETIME2
  	,`Session_End_Time` DATETIME2
  	,`Username` VARCHAR(60) NOT NULL
	,PRIMARY KEY (`Session_ID`)
  	)