CREATE TABLE Session_Tokens (
	Session_ID Varchar(60) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	User_ID Int NOT NULL,
	Create_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (User_ID) REFERENCES Users(User_ID)
  	);
